### ISSUE TITLE
IRC meetings link in docs goes to 404

### ISSUE THREAD

**Issue by robynbergeron** [ansible/community#215]
http://docs.ansible.com/ansible/latest/community.html#irc-channel

-- link to meetings page goes to a 404, as reported to me by Andrius (who I can't find on github? WUT?)

May be part of @gundalow's update plan -- notating it here at least so I don't forget. :thinking:

**Comment by mkrizek** [comment]
Already fixed here: https://github.com/ansible/ansible/pull/27264

**Comment by robynbergeron** [comment]
Assuming I am understanding correctly (which, of course, is often a bad assumption 😁) -- this is tagged for when 2.4 comes out, which is currently expected in mid-september, and that seems like kind of a long time to have a broken link, particularly when we have a bunch of new working groups starting up.

@dagwieers -- any thoughts on recreating a community/MEETINGS.md that is... I guess a pointer or at least something containing a link to plz go to community/meetings/README.md, at least until 2.4 is out? I am pretty sure that github doesn't have a way to do a symbolic link in a way that actually redirects the page in a browser since.. it's a repository, not a website, if that makes sense (I guess if we had github pages enabled it might work?)

I know it's not optimal -- like, really, far away from optimal :) But otherwise it seems like options are:

- get asked frequently about this (or, worse, folks just give up and never find their way to a meeting)
- move the file back to where it was, keep the meeting calendars in the new folder, move the file to the new spot after 2.4 is out (or just duplicate it, but that seems likely to suffer from random drift)
- Much Larger Solutions that would be super hairy to deal with like "community docs are maintained in a separate repo" or "enable github pages for ansible/community" (not even sure if that would be useful but seems like it's a maybe?)
- probably something totally easy and obvious that I have no idea about :)

Note: I am not against hairy, and in some ways the idea of having the "how to contribute" docs be not attached to a release schedule (ie: in a spot not directly attached to ansible/ansible) seems to make a lot of sense. (We don't release new versions of "community" every few months (insert your own human rolling rawhide joke here, old-school fedora friends :cowboy_hat_face:), separating from ansible/ansible 
may make helping with any community-doc-related improvements a bit more accessible for some folks, and as other projects get made inside the ansible space (lightbulb, etc.) if folks want to note them in community / contributing docs for any reason having it block on ansible releases kind of sucks. :\

And even for "how to develop code / modules / etc. to contribute" -- if any new guidelines / tips / frameworks / whatever come up that are along the lines of "for the upcoming version we're working on now, plz do $X" -- the docs for the current released version won't have that info. :\

But I don't want to leave a dead link laying around while we ponder or implement some Big Better Solution, or wait on 2.4 either. That's kind of a bummer and reflects upon us kind of awkwardly to folks who are potentially wanting to help us out. :)

**Comment by robynbergeron** [comment]
Also, all that said: I'm also not a giant fan of having a gazillion links and pieces of info all over the place to keep synchronized -- and I know we're trying to consolidate that as much as possible, at least I think. :)

**Comment by mkrizek** [comment]
@robynbergeron That fix is also backported to the temp-staging-post-2.3.2 branch (https://github.com/ansible/ansible/commit/d85bc40a044eb7b1bf2fb603ad0fa75922de33ec).

**Comment by gregdek** [comment]
Confirm that this is still broken.

So now we see a distinct potential downside to having the community docs on the official docs site: a slowness in fixing these kinds of issues. They get fixed in head, but then somehow don't manage to make their way live.
 
If we believe docs are going to be the right home for this kind of thing, we need to make sure that fixes like these make their way live quickly. Because a straight fix to a Github.io page would take 30 seconds for anyone here. 

How do we get these kinds of changes live quickly?

**Comment by gregdek** [comment]
BOOM LIVE
